chore: update enforce

diff --git a/.github/workflows/enforcer.yaml b/.github/workflows/enforcer.yaml
--- a/.github/workflows/enforcer.yaml
+++ b/.github/workflows/enforcer.yaml
@@ -10,9 +10,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Check branch
+        if: github.base_ref == 'main' && github.head_ref != 'development'
         run: |
-          if [[ ${GITHUB_HEAD_REF} != development ]] && ! [[ ${GITHUB_HEAD_REF} =~ ^hotfix/ ]]; 
-          then
-            echo "Error: Pull request must come from 'development' or 'hotfix/' branch"
-            exit 1
-          fi
+          echo "ERROR: Pull request must come from 'development' branch."
+          exit 1
